language: elixir

elixir:
  - 1.8.0

otp_release:
  - 21.1.2

env:
  - MIX_ENV=test

services:
  - postgresql

cache:
  directories:
    - _build
    - deps

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile
  - mix ecto.create
  - mix ecto.migrate

script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test
